name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # You can change this to your PHP version

      - name: Install dependencies
        run: |
          composer install

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: ${{ secrets.SONAR_ORG }}  # Your SonarCloud organization key
          token: ${{ secrets.SONAR_TOKEN }}  # SonarCloud token stored as a secret
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}  # Your SonarCloud project key

      - name: Run SonarCloud Analysis
        run: |
          sonar-scanner
