name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # or the branch you want to scan
  pull_request:
    branches:
      - main  # or the branch you want to scan

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (required for Java-based projects, adjust as needed for other languages)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Use the appropriate version for your project

      # Cache SonarCloud dependencies
      - name: Cache SonarCloud dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}  # Adjust if not using Java

      # Run SonarCloud analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: sourabhtailor  # Replace with your SonarCloud organization name
          projectKey: sourabhtailor_sonarqube         # Replace with your SonarCloud project key
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


